// Generated by gencpp from file com760cw2_group16/HomingSignalRequest.msg
// DO NOT EDIT!


#ifndef COM760CW2_GROUP16_MESSAGE_HOMINGSIGNALREQUEST_H
#define COM760CW2_GROUP16_MESSAGE_HOMINGSIGNALREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace com760cw2_group16
{
template <class ContainerAllocator>
struct HomingSignalRequest_
{
  typedef HomingSignalRequest_<ContainerAllocator> Type;

  HomingSignalRequest_()
    : x(0.0)
    , y(0.0)  {
    }
  HomingSignalRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::com760cw2_group16::HomingSignalRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::com760cw2_group16::HomingSignalRequest_<ContainerAllocator> const> ConstPtr;

}; // struct HomingSignalRequest_

typedef ::com760cw2_group16::HomingSignalRequest_<std::allocator<void> > HomingSignalRequest;

typedef boost::shared_ptr< ::com760cw2_group16::HomingSignalRequest > HomingSignalRequestPtr;
typedef boost::shared_ptr< ::com760cw2_group16::HomingSignalRequest const> HomingSignalRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::com760cw2_group16::HomingSignalRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::com760cw2_group16::HomingSignalRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace com760cw2_group16

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::com760cw2_group16::HomingSignalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::com760cw2_group16::HomingSignalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::com760cw2_group16::HomingSignalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::com760cw2_group16::HomingSignalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::com760cw2_group16::HomingSignalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::com760cw2_group16::HomingSignalRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::com760cw2_group16::HomingSignalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff8d7d66dd3e4b731ef14a45d38888b6";
  }

  static const char* value(const ::com760cw2_group16::HomingSignalRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xff8d7d66dd3e4b73ULL;
  static const uint64_t static_value2 = 0x1ef14a45d38888b6ULL;
};

template<class ContainerAllocator>
struct DataType< ::com760cw2_group16::HomingSignalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "com760cw2_group16/HomingSignalRequest";
  }

  static const char* value(const ::com760cw2_group16::HomingSignalRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::com760cw2_group16::HomingSignalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n\
float32 y\n\
";
  }

  static const char* value(const ::com760cw2_group16::HomingSignalRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::com760cw2_group16::HomingSignalRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HomingSignalRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::com760cw2_group16::HomingSignalRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::com760cw2_group16::HomingSignalRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COM760CW2_GROUP16_MESSAGE_HOMINGSIGNALREQUEST_H
