// Generated by gencpp from file com760cw2_group16/HomingSignal.msg
// DO NOT EDIT!


#ifndef COM760CW2_GROUP16_MESSAGE_HOMINGSIGNAL_H
#define COM760CW2_GROUP16_MESSAGE_HOMINGSIGNAL_H

#include <ros/service_traits.h>


#include <com760cw2_group16/HomingSignalRequest.h>
#include <com760cw2_group16/HomingSignalResponse.h>


namespace com760cw2_group16
{

struct HomingSignal
{

typedef HomingSignalRequest Request;
typedef HomingSignalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct HomingSignal
} // namespace com760cw2_group16


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::com760cw2_group16::HomingSignal > {
  static const char* value()
  {
    return "3374a123f3f3fd3591258738a2b4096b";
  }

  static const char* value(const ::com760cw2_group16::HomingSignal&) { return value(); }
};

template<>
struct DataType< ::com760cw2_group16::HomingSignal > {
  static const char* value()
  {
    return "com760cw2_group16/HomingSignal";
  }

  static const char* value(const ::com760cw2_group16::HomingSignal&) { return value(); }
};


// service_traits::MD5Sum< ::com760cw2_group16::HomingSignalRequest> should match 
// service_traits::MD5Sum< ::com760cw2_group16::HomingSignal > 
template<>
struct MD5Sum< ::com760cw2_group16::HomingSignalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::com760cw2_group16::HomingSignal >::value();
  }
  static const char* value(const ::com760cw2_group16::HomingSignalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::com760cw2_group16::HomingSignalRequest> should match 
// service_traits::DataType< ::com760cw2_group16::HomingSignal > 
template<>
struct DataType< ::com760cw2_group16::HomingSignalRequest>
{
  static const char* value()
  {
    return DataType< ::com760cw2_group16::HomingSignal >::value();
  }
  static const char* value(const ::com760cw2_group16::HomingSignalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::com760cw2_group16::HomingSignalResponse> should match 
// service_traits::MD5Sum< ::com760cw2_group16::HomingSignal > 
template<>
struct MD5Sum< ::com760cw2_group16::HomingSignalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::com760cw2_group16::HomingSignal >::value();
  }
  static const char* value(const ::com760cw2_group16::HomingSignalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::com760cw2_group16::HomingSignalResponse> should match 
// service_traits::DataType< ::com760cw2_group16::HomingSignal > 
template<>
struct DataType< ::com760cw2_group16::HomingSignalResponse>
{
  static const char* value()
  {
    return DataType< ::com760cw2_group16::HomingSignal >::value();
  }
  static const char* value(const ::com760cw2_group16::HomingSignalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COM760CW2_GROUP16_MESSAGE_HOMINGSIGNAL_H
