// Generated by gencpp from file com760cw2_group16/SetTargetPoint.msg
// DO NOT EDIT!


#ifndef COM760CW2_GROUP16_MESSAGE_SETTARGETPOINT_H
#define COM760CW2_GROUP16_MESSAGE_SETTARGETPOINT_H

#include <ros/service_traits.h>


#include <com760cw2_group16/SetTargetPointRequest.h>
#include <com760cw2_group16/SetTargetPointResponse.h>


namespace com760cw2_group16
{

struct SetTargetPoint
{

typedef SetTargetPointRequest Request;
typedef SetTargetPointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetTargetPoint
} // namespace com760cw2_group16


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::com760cw2_group16::SetTargetPoint > {
  static const char* value()
  {
    return "3374a123f3f3fd3591258738a2b4096b";
  }

  static const char* value(const ::com760cw2_group16::SetTargetPoint&) { return value(); }
};

template<>
struct DataType< ::com760cw2_group16::SetTargetPoint > {
  static const char* value()
  {
    return "com760cw2_group16/SetTargetPoint";
  }

  static const char* value(const ::com760cw2_group16::SetTargetPoint&) { return value(); }
};


// service_traits::MD5Sum< ::com760cw2_group16::SetTargetPointRequest> should match 
// service_traits::MD5Sum< ::com760cw2_group16::SetTargetPoint > 
template<>
struct MD5Sum< ::com760cw2_group16::SetTargetPointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::com760cw2_group16::SetTargetPoint >::value();
  }
  static const char* value(const ::com760cw2_group16::SetTargetPointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::com760cw2_group16::SetTargetPointRequest> should match 
// service_traits::DataType< ::com760cw2_group16::SetTargetPoint > 
template<>
struct DataType< ::com760cw2_group16::SetTargetPointRequest>
{
  static const char* value()
  {
    return DataType< ::com760cw2_group16::SetTargetPoint >::value();
  }
  static const char* value(const ::com760cw2_group16::SetTargetPointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::com760cw2_group16::SetTargetPointResponse> should match 
// service_traits::MD5Sum< ::com760cw2_group16::SetTargetPoint > 
template<>
struct MD5Sum< ::com760cw2_group16::SetTargetPointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::com760cw2_group16::SetTargetPoint >::value();
  }
  static const char* value(const ::com760cw2_group16::SetTargetPointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::com760cw2_group16::SetTargetPointResponse> should match 
// service_traits::DataType< ::com760cw2_group16::SetTargetPoint > 
template<>
struct DataType< ::com760cw2_group16::SetTargetPointResponse>
{
  static const char* value()
  {
    return DataType< ::com760cw2_group16::SetTargetPoint >::value();
  }
  static const char* value(const ::com760cw2_group16::SetTargetPointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COM760CW2_GROUP16_MESSAGE_SETTARGETPOINT_H
