(cl:defpackage com760cw2_group16-srv
  (:use )
  (:export
   "HOMINGSIGNAL"
   "<HOMINGSIGNAL-REQUEST>"
   "HOMINGSIGNAL-REQUEST"
   "<HOMINGSIGNAL-RESPONSE>"
   "HOMINGSIGNAL-RESPONSE"
   "SETTARGETPOINT"
   "<SETTARGETPOINT-REQUEST>"
   "SETTARGETPOINT-REQUEST"
   "<SETTARGETPOINT-RESPONSE>"
   "SETTARGETPOINT-RESPONSE"
  ))

