(cl:defpackage com760cw2_group16-srv
  (:use )
  (:export
   "HOMINGSIGNAL"
   "<HOMINGSIGNAL-REQUEST>"
   "HOMINGSIGNAL-REQUEST"
   "<HOMINGSIGNAL-RESPONSE>"
   "HOMINGSIGNAL-RESPONSE"
   "SETBUGMODE"
   "<SETBUGMODE-REQUEST>"
   "SETBUGMODE-REQUEST"
   "<SETBUGMODE-RESPONSE>"
   "SETBUGMODE-RESPONSE"
  ))

